services:
  app:
    build: .
    image: spliit:latest
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env
    environment:
      - PORT=3000
      - DATABASE_URL=file:/data/spliit.db
    volumes:
      - ./spliit-data:/data
